### ISSUE TITLE
[tablet] Implement Convergence of Main Tabs

### ISSUE THREAD

**Issue by krnekhelesh** [krnekhelesh/flashback#1]
Flashback needs to be converged across the tablet where the main tabs Home, Movies, TV and Celeb utilise the extra screen width. This can be done by adding a sidebar housing the categories which were previously shown in carousels.

**Comment by iBelieve** [comment]
What's the ETA?

**Comment by krnekhelesh** [comment]
Probably 0.5...(commenting from project dashboard)

**Comment by krnekhelesh** [comment]
This has been implemented in the devel branch. The main tabs are now convergent across the tablet and the desktop :)
