### ISSUE TITLE
Tablet is spelt incorrectly (talbet) on the Github.io webpage

### ISSUE THREAD

**Issue by VictorThompson** [krnekhelesh/flashback#4]
The app's website states the following:

"Works everywhere.

Try it on Smartphones, Talbets and Desktop.
On Ubuntu Desktop and Ubuntu Touch."

Talbet (sic) is spelt incorrectly.

**Comment by krnekhelesh** [comment]
Thanks for spotting this.

**Comment by krnekhelesh** [comment]
Fixed
