### ISSUE TITLE
Toolbar doesn't show up on the home page

### ISSUE THREAD

**Issue by iBelieve** [krnekhelesh/flashback#7]
When I open the app, I see a message saying no Trakt account is configured, with a nice animated arrow pointing to what I assume is an add account or settings button in the toolbar. But I'm unable to open the toolbar. It works fine on other tabs, but not on the home page.

I'm using v0.4 on Ubuntu 14.04 from the PPA.

**Comment by krnekhelesh** [comment]
Ah yes, I checked that the toolbar is locked but not opened which is why you weren't able to open it. I have got a fix in the devel branch. Going to push to release in the 0.4.1 release.

**Comment by krnekhelesh** [comment]
The devel branch has moved to the new headers. So this bug is fixed as a result of that.
